### PR TITLE
added route middleware and prefix to config file

### LINKED ISSUE #27: Cant set route middleware and prefix
It would be nice to control which middleware to use on the route and its prefix.
Sending a PR for this in a minute

### PR DESCRIPTION
**Pull request by cacpmw**
This makes route prefix and middleware editable on the config file.
Closes #27

### CODE REVIEW

**Comment by ichtrojan** [comment]
Hi @cacpmw, 

I have merged a pending PR, can you update yours.

**Comment by cacpmw** [comment]
> Hi @cacpmw,
> 
> I have merged a pending PR, can you update yours.

@ichtrojan done

**Comment by ichtrojan** [comment]
I’d create a release for these updates and update the readme tomorrow. 

Thanks

**Comment by cacpmw** [comment]
@ichtrojan would you do this today? I really need that update :D

**Comment by ichtrojan** [comment]
It’s all done 🙂

**Comment by cacpmw** [comment]
Thanks a bunch bro!

**Pull request merged**
